services:
  grafana:
    image: grafana/grafana:latest
    container_name: ottermq_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - ottermq_network
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana_data:

# networks:
#   ottermq_network:
#     external: true