// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Add a user",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User added successfully",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bindings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all bindings for the specified exchange",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bindings"
                ],
                "summary": "List all bindings for an exchange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BindingListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bind a queue to an exchange with the specified routing key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bindings"
                ],
                "summary": "Bind a queue to an exchange",
                "parameters": [
                    {
                        "description": "Binding to create",
                        "name": "binding",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateBindingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a binding from an exchange to a queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bindings"
                ],
                "summary": "Delete a binding",
                "parameters": [
                    {
                        "description": "Binding to delete",
                        "name": "binding",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteBindingRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/channels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all channels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "List all channels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ChannelListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list channels",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/channels/{vhost}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all channels for a specific VHost",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "List channels by VHost",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ChannelListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid or malformed request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "VHost not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get channels",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connections": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all connections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "List all connections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list connections",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connections/{name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get details of a specific connection by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Get connection details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionInfoDTO"
                        }
                    },
                    "400": {
                        "description": "Connection ID is required",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Connection not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get connection",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Close a specific connection by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Close a connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reason for closing the connection",
                        "name": "reason",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Connection ID is required",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to close connection",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connections/{name}/channels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all channels for a specific connection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "List all channels for a specific connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ChannelListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Connection not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list channels",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connections/{name}/channels/{channel}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get details of a specific channel by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "Get channel details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Channel ID",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ChannelInfoDTO"
                        }
                    },
                    "400": {
                        "description": "Channel ID is required",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Channel not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get channel",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/consumers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all consumers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "List all consumers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConsumerListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list consumers",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/consumers/{vhost}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of consumers for a specific queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "List consumers for a specific queue",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConsumerListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list consumers for queue",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all exchanges",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "List all exchanges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ExchangeListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list exchanges",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{vhost}/{exchange}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an exchange by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Get an exchange",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Exchange name",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ExchangeDTO"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get exchange",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new exchange with the specified name and type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Create a new exchange",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Exchange name",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exchange to create",
                        "name": "exchange",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exchange created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid or malformed request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an exchange with the specified name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Delete an exchange",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Exchange name",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{vhost}/{exchange}/bindings/source": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all bindings where the specified exchange is the source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Get bindings where the exchange is the source",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Exchange name",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BindingListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get bindings",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{vhost}/{exchange}/publish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Publish a message to the specified exchange with a routing key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Publish a message to an exchange",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Exchange name",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message details",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PublishMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve basic information about the message broker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "overview"
                ],
                "summary": "Get broker overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OverviewDTO"
                        }
                    },
                    "500": {
                        "description": "Failed to get broker information",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/overview/broker": {
            "get": {
                "description": "Retrieve basic information about the message broker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "overview"
                ],
                "summary": "Get basic broker information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OverviewBrokerDetails"
                        }
                    },
                    "500": {
                        "description": "Failed to get broker information",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all queues",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "List all queues",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QueueListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list queues",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/{vhost}/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new queue with a generated name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Create a new queue with generated name",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "description": "Queue to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateQueueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Queue not found in vhost",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/{vhost}/{queueName}/consumers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of consumers for a specific queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "List consumers for a specific queue",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Queue Name",
                        "name": "queueName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConsumerListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Object not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list consumers for queue",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/{vhost}/{queue}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a queue by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Get a queue",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Queue name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QueueDTO"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list queues",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new queue with the specified name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Create a new queue",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Queue name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Queue to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateQueueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Queue not found in vhost",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a queue with the specified name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Delete a queue",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Queue name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "If true, the server will only delete the queue if it has no consumers",
                        "name": "ifUnused",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "If true, the server will only delete the queue if it is empty",
                        "name": "ifEmpty",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/{vhost}/{queue}/bindings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all bindings for the specified queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "List all bindings for a queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Queue name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BindingListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/{vhost}/{queue}/content": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove all messages from a queue with the specified name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Purge a queue",
                "parameters": [
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Queue name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Number of messages purged",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/{vhost}/{queue}/get": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Consume a message from the specified queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Consume a message from a queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Queue name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "/",
                        "description": "VHost name",
                        "name": "vhost",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Queue name is required",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No messages in queue",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.BrokerSnapshot": {
            "type": "object",
            "properties": {
                "ack_rate": {
                    "type": "number"
                },
                "channel_count": {
                    "type": "integer"
                },
                "channel_rate": {
                    "type": "number"
                },
                "connection_count": {
                    "type": "integer"
                },
                "connection_rate": {
                    "type": "number"
                },
                "consumer_count": {
                    "type": "integer"
                },
                "delivery_rate": {
                    "type": "number"
                },
                "exchange_count": {
                    "type": "integer"
                },
                "message_count": {
                    "description": "Broker-wide gauges",
                    "type": "integer"
                },
                "nack_rate": {
                    "type": "number"
                },
                "publish_rate": {
                    "description": "Broker-wide rates (current)",
                    "type": "number"
                },
                "queue_count": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.BindingDTO": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "destination": {
                    "description": "Destination = Queue name (or Exchange name if exchange-to-exchange binding )",
                    "type": "string"
                },
                "destination_type": {
                    "description": "\"queue\" or \"exchange\"",
                    "type": "string"
                },
                "properties_key": {
                    "description": "Hash for idempotency",
                    "type": "string"
                },
                "routing_key": {
                    "type": "string"
                },
                "source": {
                    "description": "Source = Exchange name",
                    "type": "string"
                },
                "vhost": {
                    "type": "string"
                }
            }
        },
        "models.BindingListResponse": {
            "type": "object",
            "properties": {
                "bindings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BindingDTO"
                    }
                }
            }
        },
        "models.BrokerConfigOverview": {
            "type": "object",
            "properties": {
                "amqp_port": {
                    "type": "string"
                },
                "channel_max": {
                    "type": "integer"
                },
                "enabled_features": {
                    "description": "e.g., [\"DLX\", \"TTL\", \"QLL\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "frame_max": {
                    "type": "integer"
                },
                "http_contexts": {
                    "description": "e.g., Context:path [\"management:/\", \"swagger:/\", \"prometheus:/\"]",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HttpContext"
                    }
                },
                "http_port": {
                    "type": "string"
                },
                "persistence_backend": {
                    "description": "\"json\", \"memento\" (future)",
                    "type": "string"
                },
                "queue_buffer_size": {
                    "type": "integer"
                },
                "ssl": {
                    "type": "boolean"
                }
            }
        },
        "models.ChannelDetailDTO": {
            "type": "object",
            "properties": {
                "ack_rate": {
                    "type": "number"
                },
                "confirm_rate": {
                    "type": "number"
                },
                "connection_name": {
                    "type": "string"
                },
                "deliver_rate": {
                    "type": "number"
                },
                "number": {
                    "description": "channel number",
                    "type": "integer"
                },
                "prefetch_count": {
                    "type": "integer"
                },
                "publish_rate": {
                    "description": "Stats",
                    "type": "number"
                },
                "state": {
                    "description": "\"running\", \"flow\", \"closing\"",
                    "type": "string"
                },
                "unacked_count": {
                    "type": "integer"
                },
                "unconfirmed_count": {
                    "description": "Details",
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                },
                "vhost": {
                    "type": "string"
                }
            }
        },
        "models.ChannelInfoDTO": {
            "type": "object",
            "properties": {
                "connection_name": {
                    "type": "string"
                },
                "number": {
                    "description": "channel number",
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.ChannelListResponse": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ChannelDetailDTO"
                    }
                }
            }
        },
        "models.ConnectionInfoDTO": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "integer"
                },
                "connected_at": {
                    "type": "string"
                },
                "last_heartbeat": {
                    "type": "string"
                },
                "name": {
                    "description": "ip",
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                },
                "state": {
                    "description": "\"disconnected\" or \"running\"",
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "vhost": {
                    "type": "string"
                }
            }
        },
        "models.ConnectionListResponse": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConnectionInfoDTO"
                    }
                }
            }
        },
        "models.ConsumerDTO": {
            "type": "object",
            "properties": {
                "ack_required": {
                    "description": "!NoAck",
                    "type": "boolean"
                },
                "active": {
                    "type": "boolean"
                },
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "channel_details": {
                    "$ref": "#/definitions/models.ChannelInfoDTO"
                },
                "consumer_tag": {
                    "type": "string"
                },
                "exclusive": {
                    "type": "boolean"
                },
                "prefetch_count": {
                    "type": "integer"
                },
                "queue_name": {
                    "type": "string"
                }
            }
        },
        "models.ConsumerListResponse": {
            "type": "object",
            "properties": {
                "consumers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConsumerDTO"
                    }
                }
            }
        },
        "models.CreateBindingRequest": {
            "type": "object",
            "required": [
                "destination",
                "source"
            ],
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "destination": {
                    "description": "Queue (?or Exchange too??)",
                    "type": "string"
                },
                "routing_key": {
                    "type": "string"
                },
                "source": {
                    "description": "Exchange",
                    "type": "string"
                },
                "vhost": {
                    "description": "Optional; defaults to \"/\"",
                    "type": "string"
                }
            }
        },
        "models.CreateExchangeRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "auto_delete": {
                    "type": "boolean"
                },
                "durable": {
                    "type": "boolean"
                },
                "no_wait": {
                    "description": "not needed for management API. Included for completeness",
                    "type": "boolean"
                },
                "passive": {
                    "description": "Properties",
                    "type": "boolean"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "direct",
                        "fanout",
                        "topic",
                        "headers"
                    ]
                }
            }
        },
        "models.CreateQueueRequest": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "auto_delete": {
                    "type": "boolean",
                    "default": false
                },
                "durable": {
                    "type": "boolean",
                    "default": false
                },
                "max_length": {
                    "description": "Convenience fields (auto-mapped to arguments)",
                    "type": "integer"
                },
                "message_ttl": {
                    "type": "integer"
                },
                "passive": {
                    "description": "Properties/flags",
                    "type": "boolean",
                    "default": false
                },
                "x-dead-letter-exchange": {
                    "type": "string"
                },
                "x-dead-letter-routing-key": {
                    "type": "string"
                }
            }
        },
        "models.DeleteBindingRequest": {
            "type": "object",
            "required": [
                "destination",
                "source"
            ],
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "destination": {
                    "description": "Queue (?or Exchange too??)",
                    "type": "string"
                },
                "routing_key": {
                    "type": "string"
                },
                "source": {
                    "description": "Exchange",
                    "type": "string"
                },
                "vhost": {
                    "description": "Optional; defaults to \"/\"",
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.ExchangeDTO": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "auto_delete": {
                    "type": "boolean"
                },
                "durable": {
                    "description": "Properties/flags",
                    "type": "boolean"
                },
                "internal": {
                    "type": "boolean"
                },
                "message_stats_in": {
                    "description": "Stats",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MessageStats"
                        }
                    ]
                },
                "message_stats_out": {
                    "$ref": "#/definitions/models.MessageStats"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "vhost": {
                    "description": "Identity",
                    "type": "string"
                }
            }
        },
        "models.ExchangeListResponse": {
            "type": "object",
            "properties": {
                "exchanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExchangeDTO"
                    }
                }
            }
        },
        "models.HttpContext": {
            "type": "object",
            "properties": {
                "bound_to": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                }
            }
        },
        "models.MessageStats": {
            "type": "object",
            "properties": {
                "deliver_get": {
                    "type": "integer"
                },
                "deliver_get_details.rate": {
                    "type": "number"
                },
                "publish": {
                    "type": "integer"
                },
                "publish_details.rate": {
                    "type": "number"
                }
            }
        },
        "models.NodeInfo": {
            "type": "object",
            "properties": {
                "enabled_plugins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message_rates": {
                    "description": "message rates strategy",
                    "type": "string"
                }
            }
        },
        "models.OverviewBrokerDetails": {
            "type": "object",
            "properties": {
                "commit_hash": {
                    "type": "string"
                },
                "commit_number": {
                    "type": "string"
                },
                "data_dir": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "uptime_secs": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.OverviewConnectionStats": {
            "type": "object",
            "properties": {
                "amqp091": {
                    "description": "Protocol breakdown",
                    "type": "integer"
                },
                "client_connections": {
                    "description": "Excludes management connections",
                    "type": "integer"
                },
                "closing": {
                    "type": "integer"
                },
                "running": {
                    "description": "By state",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.OverviewDTO": {
            "type": "object",
            "properties": {
                "broker": {
                    "$ref": "#/definitions/models.OverviewBrokerDetails"
                },
                "configuration": {
                    "$ref": "#/definitions/models.BrokerConfigOverview"
                },
                "connection_stats": {
                    "$ref": "#/definitions/models.OverviewConnectionStats"
                },
                "message_stats": {
                    "$ref": "#/definitions/models.OverviewMessageStats"
                },
                "metrics": {
                    "$ref": "#/definitions/metrics.BrokerSnapshot"
                },
                "node": {
                    "$ref": "#/definitions/models.OverviewNodeDetails"
                },
                "object_totals": {
                    "$ref": "#/definitions/models.OverviewObjectTotals"
                }
            }
        },
        "models.OverviewMessageStats": {
            "type": "object",
            "properties": {
                "messages_ready": {
                    "description": "Current state (easy to calculate now)",
                    "type": "integer"
                },
                "messages_total": {
                    "description": "Ready + Unacked",
                    "type": "integer"
                },
                "messages_unacknowledged": {
                    "description": "Sum of unacked",
                    "type": "integer"
                },
                "queue_stats": {
                    "description": "Per-queue breakdown",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.QueueMessageBreakdown"
                    }
                }
            }
        },
        "models.OverviewNodeDetails": {
            "type": "object",
            "properties": {
                "cores": {
                    "type": "integer"
                },
                "disk_available": {
                    "description": "in bytes",
                    "type": "integer"
                },
                "disk_total": {
                    "description": "in bytes",
                    "type": "integer"
                },
                "fd_limit": {
                    "type": "integer"
                },
                "fd_used": {
                    "type": "integer"
                },
                "goroutines": {
                    "type": "integer"
                },
                "goroutines_limit": {
                    "type": "integer"
                },
                "info": {
                    "$ref": "#/definitions/models.NodeInfo"
                },
                "memory_limit": {
                    "description": "in bytes",
                    "type": "integer"
                },
                "memory_usage": {
                    "description": "in bytes",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "uptime_secs": {
                    "type": "integer"
                }
            }
        },
        "models.OverviewObjectTotals": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "integer"
                },
                "connections": {
                    "type": "integer"
                },
                "consumers": {
                    "type": "integer"
                },
                "exchanges": {
                    "type": "integer"
                },
                "queues": {
                    "type": "integer"
                }
            }
        },
        "models.PublishMessageRequest": {
            "type": "object",
            "required": [
                "payload"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "content_encoding": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "correlation_id": {
                    "type": "string"
                },
                "delivery_mode": {
                    "description": "1=transient, 2=persistent",
                    "type": "integer"
                },
                "expiration": {
                    "description": "TTL in milliseconds as string",
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message_id": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "reply_to": {
                    "type": "string"
                },
                "routing_key": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.QueueDTO": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "auto_delete": {
                    "type": "boolean"
                },
                "consumers": {
                    "description": "Consumers stats",
                    "type": "integer"
                },
                "dead_letter_exchange": {
                    "description": "DLX Configuration (extracted for convenience)",
                    "type": "string"
                },
                "dead_letter_routing_key": {
                    "type": "string"
                },
                "durable": {
                    "description": "Properties/flags",
                    "type": "boolean"
                },
                "exclusive": {
                    "type": "boolean"
                },
                "max_length": {
                    "description": "Queue Length Limit (QLL AKA Max Length)",
                    "type": "integer"
                },
                "max_priority": {
                    "description": "Priority queue configuration",
                    "type": "integer"
                },
                "message_ttl": {
                    "description": "TTL Configuration",
                    "type": "integer"
                },
                "messages": {
                    "description": "Message counts (RabbitMQ compatible field names)",
                    "type": "integer"
                },
                "messages_persistent": {
                    "type": "integer"
                },
                "messages_ready": {
                    "description": "Alias",
                    "type": "integer"
                },
                "messages_total": {
                    "description": "Ready + Unacked",
                    "type": "integer"
                },
                "messages_unacked": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner_connection": {
                    "description": "Metadata",
                    "type": "string"
                },
                "persistence_enabled": {
                    "type": "boolean"
                },
                "state": {
                    "description": "State",
                    "type": "string"
                },
                "vhost": {
                    "description": "Identity",
                    "type": "string"
                }
            }
        },
        "models.QueueListResponse": {
            "type": "object",
            "properties": {
                "queues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.QueueDTO"
                    }
                }
            }
        },
        "models.QueueMessageBreakdown": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "integer"
                },
                "messages_unacknowledged": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "vhost": {
                    "type": "string"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.UnauthorizedErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.UserCreateRequest": {
            "type": "object",
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserListResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserSummary"
                    }
                }
            }
        },
        "models.UserSummary": {
            "type": "object",
            "properties": {
                "has_password": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "OtterMQ API",
	Description:      "API documentation for OtterMQ broker",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
